import { createDocument, createNode, createScreen, getActiveScreen, makeAiHandoff, sanitizeDocument } from './model.js';
import { downloadText, safeFileName, screenToSvg, svgToPngBlob, downloadBlob } from './export.js';
import { loadAutosave, saveAutosave } from './storage.js';

const $ = (q) => document.querySelector(q);
const $$ = (q) => [...document.querySelectorAll(q)];
const E = {
  title: $('#document-title'), stage: $('#stage'), shell: $('#artboard-shell'), board: $('#artboard'), preview: $('#draw-preview'),
  screens: $('#screen-list'), layers: $('#layer-list'), count: $('#layer-count'), inspector: $('#inspector'), hint: $('#status-hint'),
  zoom: $('#zoom-label'), grid: $('#toggle-grid'), tooltip: $('#tooltip'), tipTitle: $('#tooltip-title'), tipBody: $('#tooltip-body'),
  toast: $('#toast'), file: $('#file-input')
};
const saved = loadAutosave();
let doc;
try { doc = saved?.document ? sanitizeDocument(saved.document) : createDocument(); } catch { doc = createDocument(); }
const S = {
  doc, screenId: saved?.activeScreenId || doc.screens[0].id, selected: null, tool: 'select', zoom: .65, grid: true, snap: 8,
  history: [], future: [], gesture: null, pan: null, space: false, tipTimer: null
};
const HINT = {
  select: 'Select · click, move, resize, or double-click text.', frame: 'Frame · drag a semantic region.',
  box: 'Box · drag, release, then type immediately.', text: 'Text · click or drag, then type.', image: 'Image · draw an asset placeholder.'
};
const esc = (v='') => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const screen = () => getActiveScreen(S.doc, S.screenId);
const node = () => screen().nodes.find(n => n.id === S.selected) || null;
const snap = (n) => S.grid ? Math.round(n / S.snap) * S.snap : Math.round(n);
const persist = () => saveAutosave(S.doc, S.screenId);
function toast(text) { E.toast.textContent=text; E.toast.hidden=false; clearTimeout(toast.t); toast.t=setTimeout(()=>E.toast.hidden=true,1400); }
function status(text) { E.hint.textContent = text || HINT[S.tool]; }
function snapshot() { S.history.push(structuredClone(S.doc)); if(S.history.length>80)S.history.shift(); S.future=[]; }
function change(fn) { snapshot(); fn(); S.doc.updatedAt=new Date().toISOString(); persist(); render(); }
function undo(){ if(!S.history.length)return; S.future.push(structuredClone(S.doc)); S.doc=S.history.pop(); S.selected=null; persist(); render(); toast('Undo'); }
function redo(){ if(!S.future.length)return; S.history.push(structuredClone(S.doc)); S.doc=S.future.pop(); S.selected=null; persist(); render(); toast('Redo'); }
function setTool(tool){ S.tool=tool; S.gesture=null; E.preview.hidden=true; $$('.tool-button').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool)); E.stage.dataset.tool=tool; status(); }
function setZoom(z){ S.zoom=Math.max(.1,Math.min(2.4,z)); renderBoard(); renderStatus(); }
function fit(){ const sc=screen(); setZoom(Math.min(1,(E.stage.clientWidth-144)/sc.width,(E.stage.clientHeight-144)/sc.height)); }

function render(){ E.title.value=S.doc.name; renderScreens(); renderLayers(); renderBoard(); renderInspector(); renderStatus(); setTool(S.tool); }
function renderScreens(){ E.screens.innerHTML=S.doc.screens.map(sc=>`<div class="screen-row ${sc.id===S.screenId?'active':''}" data-screen="${esc(sc.id)}" data-tooltip="${esc(sc.name)}|${sc.width} × ${sc.height} · ${esc(sc.platform)}"><span class="screen-icon">▱</span><span class="screen-name">${esc(sc.name)}</span><span class="screen-size">${sc.width}×${sc.height}</span></div>`).join(''); }
function renderLayers(){ const sc=screen(); E.count.textContent=sc.nodes.length; E.layers.innerHTML=[...sc.nodes].reverse().map(n=>`<div class="layer-row ${S.selected===n.id?'selected':''} ${n.hidden?'hidden-layer':''}" data-node="${esc(n.id)}" data-tooltip="${esc(n.name)}|${esc(n.role||n.type)}${n.note?' · '+esc(n.note.slice(0,80)):''}"><span class="layer-kind">${({frame:'F',box:'B',text:'T',image:'I'})[n.type]}</span><span class="layer-name">${esc(n.name||n.text)}</span><button class="layer-action ${n.hidden?'active':''}" data-hide="${esc(n.id)}">${n.hidden?'○':'●'}</button><button class="layer-action ${n.locked?'active':''}" data-lock="${esc(n.id)}">${n.locked?'◆':'◇'}</button></div>`).join(''); }
function shapeStyle(n){ const s=n.style||{}; return `background:${n.type==='text'?'transparent':s.fill};border:${n.type==='text'?'0':`1px ${n.type==='frame'?'dashed':'solid'} ${s.stroke}`};border-radius:${s.radius}px;color:${s.textColor};font-size:${s.fontSize}px;text-align:${s.textAlign}`; }
function renderBoard(){ const sc=screen(); E.shell.style.width=`${sc.width*S.zoom}px`; E.shell.style.height=`${sc.height*S.zoom}px`; Object.assign(E.board.style,{width:`${sc.width}px`,height:`${sc.height}px`,transform:`scale(${S.zoom})`,backgroundColor:sc.background}); E.board.classList.toggle('grid-enabled',S.grid); E.board.innerHTML=sc.nodes.filter(n=>!n.hidden).map(n=>{ const b=n.bounds, sel=S.selected===n.id, label=n.text||(n.type==='frame'?n.name:''); return `<div class="node type-${n.type} ${sel?'selected':''} ${n.locked?'locked':''}" data-node="${esc(n.id)}" data-tooltip="${esc(n.name)}|${esc(n.role||n.type)} · ${b.x},${b.y} · ${b.width}×${b.height}${n.note?' · '+esc(n.note.slice(0,60)):''}" style="left:${b.x}px;top:${b.y}px;width:${b.width}px;height:${b.height}px"><div class="node-shape" style="${shapeStyle(n)}">${n.type==='image'?'<div class="image-cross"></div>':''}<div class="node-text">${esc(label)}</div></div>${sel?`<div class="node-hover-tag"><span>${esc(n.name)}</span>${n.role?`<span class="role">${esc(n.role)}</span>`:''}</div>${n.locked?'':'<span class="resize-handle" data-resize="'+esc(n.id)+'" data-handle="se"></span>'}`:''}</div>`}).join(''); }
const field=(label,path,value,type='text')=>`<label class="field-row"><span class="field-label">${label}</span><input class="field-control" data-field="${path}" type="${type}" value="${esc(value)}"></label>`;
const area=(label,path,value)=>`<label class="field-row"><span class="field-label">${label}</span><textarea class="field-textarea" data-field="${path}">${esc(value||'')}</textarea></label>`;
function renderInspector(){ const sc=screen(), n=node(); if(!n){ E.inspector.innerHTML=`<div class="inspect-title"><div class="inspect-kind">S</div><div class="inspect-title-text"><div class="inspect-name">${esc(sc.name)}</div><div class="inspect-subtitle">${sc.width} × ${sc.height} · ${esc(sc.platform)}</div></div></div><section class="inspect-section"><div class="inspect-section-title">Screen</div><div class="field-grid single">${field('Name','screen.name',sc.name)}</div><div class="field-grid" style="margin-top:7px">${field('Width','screen.width',sc.width,'number')}${field('Height','screen.height',sc.height,'number')}</div></section><section class="inspect-section"><div class="inspect-section-title">Fast loop</div><div style="color:#8f929c;font-size:11px;line-height:1.6"><b>B</b> draw → type → <b>Enter</b>.<br><b>V</b> select → move / resize.<br>Add <b>Role</b> only when meaning is ambiguous.<br><b>Copy for AI</b> sends exact intent.</div></section>`; return; }
 E.inspector.innerHTML=`<div class="inspect-title"><div class="inspect-kind">${n.type[0]}</div><div class="inspect-title-text"><div class="inspect-name">${esc(n.name)}</div><div class="inspect-subtitle">${esc(n.role||n.type)} · ${n.bounds.width} × ${n.bounds.height}</div></div></div><section class="inspect-section"><div class="inspect-section-title">Identity</div><div class="field-grid single">${field('Name','node.name',n.name)}</div><div class="field-grid single" style="margin-top:7px">${field('Role','node.role',n.role)}</div></section><section class="inspect-section"><div class="inspect-section-title">Bounds</div><div class="field-grid">${field('X','node.bounds.x',n.bounds.x,'number')}${field('Y','node.bounds.y',n.bounds.y,'number')}</div><div class="field-grid" style="margin-top:7px">${field('W','node.bounds.width',n.bounds.width,'number')}${field('H','node.bounds.height',n.bounds.height,'number')}</div></section><section class="inspect-section"><div class="inspect-section-title">Intent</div>${area('Text','node.text',n.text)}<div style="margin-top:7px">${area('Note / behavior','node.note',n.note)}</div></section><section class="inspect-section"><div class="inspect-actions"><button class="inspect-button" data-action="duplicate">Duplicate</button><button class="inspect-button" data-action="lock">${n.locked?'Unlock':'Lock'}</button><button class="inspect-button danger" data-action="delete">Delete</button></div></section>`; }
function renderStatus(){ E.zoom.textContent=`${Math.round(S.zoom*100)}%`; E.grid.textContent=S.grid?`Grid ${S.snap}`:'Grid off'; E.grid.classList.toggle('active',S.grid); }
function point(ev){ const r=E.board.getBoundingClientRect(); return {x:Math.max(0,Math.min(screen().width,(ev.clientX-r.left)/S.zoom)),y:Math.max(0,Math.min(screen().height,(ev.clientY-r.top)/S.zoom))}; }
function startTextEdit(id,selectAll=false){ const n=screen().nodes.find(x=>x.id===id); if(!n)return; const t=document.createElement('textarea'); t.className=`inline-editor type-${n.type}`; Object.assign(t.style,{left:`${n.bounds.x}px`,top:`${n.bounds.y}px`,width:`${n.bounds.width}px`,height:`${n.bounds.height}px`,fontSize:`${n.style.fontSize}px`,textAlign:n.style.textAlign}); t.value=n.text||''; E.board.append(t); t.focus(); selectAll?t.select():t.setSelectionRange(t.value.length,t.value.length); const old=n.text; let done=false; const finish=(save)=>{if(done)return;done=true;const v=t.value;t.remove();if(save&&v!==old)change(()=>screen().nodes.find(x=>x.id===id).text=v);else renderBoard();}; t.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();finish(false)}else if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();finish(true)}}; t.onblur=()=>finish(true); status('Editing · Enter commits · Shift+Enter newline · Esc cancels'); }
function beginDraw(ev){ if(S.tool==='select'||ev.button!==0)return; const p=point(ev); S.gesture={kind:'draw',start:p,current:p}; ev.preventDefault(); }
function drawMove(ev){ const g=S.gesture;if(g?.kind!=='draw')return;g.current=point(ev);const x=Math.min(g.start.x,g.current.x),y=Math.min(g.start.y,g.current.y),w=Math.abs(g.current.x-g.start.x),h=Math.abs(g.current.y-g.start.y),r=E.board.getBoundingClientRect();E.preview.hidden=false;Object.assign(E.preview.style,{left:`${r.left+x*S.zoom}px`,top:`${r.top+y*S.zoom}px`,width:`${w*S.zoom}px`,height:`${h*S.zoom}px`});status(`${S.tool} · ${Math.round(w)} × ${Math.round(h)}`);}
function endDraw(ev){ const g=S.gesture;if(g?.kind!=='draw')return;S.gesture=null;E.preview.hidden=true;const p=point(ev),d={frame:[320,240],box:[180,72],text:[180,32],image:[240,160]}[S.tool];let x=snap(Math.min(g.start.x,p.x)),y=snap(Math.min(g.start.y,p.y)),w=snap(Math.abs(p.x-g.start.x)),h=snap(Math.abs(p.y-g.start.y));if(w<8&&h<8)[w,h]=d;w=Math.max(8,w);h=Math.max(8,h);let id;change(()=>{const n=createNode(S.tool,{x,y,width:w,height:h},{text:S.tool==='frame'?'':undefined});screen().nodes.push(n);S.selected=id=n.id});if(['box','text'].includes(S.tool))requestAnimationFrame(()=>startTextEdit(id,true));}
function beginNode(ev,id){ if(S.tool!=='select'||ev.button!==0)return;const n=screen().nodes.find(x=>x.id===id);S.selected=id;render();if(n.locked)return status('Locked · unlock in Layers or Inspector.');S.gesture={kind:'move',id,start:{x:ev.clientX,y:ev.clientY},bounds:{...n.bounds},before:structuredClone(S.doc)};ev.stopPropagation();ev.preventDefault();}
function moveNode(ev){const g=S.gesture;if(g?.kind!=='move')return;const n=screen().nodes.find(x=>x.id===g.id),dx=snap((ev.clientX-g.start.x)/S.zoom),dy=snap((ev.clientY-g.start.y)/S.zoom);n.bounds.x=g.bounds.x+dx;n.bounds.y=g.bounds.y+dy;renderBoard();renderInspector();status(`Move · Δ ${dx}, ${dy}`);}
function endMove(){const g=S.gesture;if(g?.kind!=='move')return;S.gesture=null;if(JSON.stringify(g.before)!==JSON.stringify(S.doc)){S.history.push(g.before);S.future=[];persist();}render();}
function beginResize(ev,id){const n=screen().nodes.find(x=>x.id===id);S.gesture={kind:'resize',id,start:{x:ev.clientX,y:ev.clientY},bounds:{...n.bounds},before:structuredClone(S.doc)};ev.stopPropagation();ev.preventDefault();}
function resizeMove(ev){const g=S.gesture;if(g?.kind!=='resize')return;const n=screen().nodes.find(x=>x.id===g.id);n.bounds.width=Math.max(8,snap(g.bounds.width+(ev.clientX-g.start.x)/S.zoom));n.bounds.height=Math.max(8,snap(g.bounds.height+(ev.clientY-g.start.y)/S.zoom));renderBoard();renderInspector();status(`Resize · ${n.bounds.width} × ${n.bounds.height}`);}
function endResize(){const g=S.gesture;if(g?.kind!=='resize')return;S.gesture=null;S.history.push(g.before);S.future=[];persist();render();}
function del(){if(!S.selected)return;change(()=>{screen().nodes=screen().nodes.filter(n=>n.id!==S.selected);S.selected=null});}
function duplicate(){const n=node();if(!n)return;change(()=>{const c=structuredClone(n);c.id=`${n.type}_${Date.now().toString(36)}`;c.name=`${n.name} copy`;c.bounds.x+=16;c.bounds.y+=16;screen().nodes.push(c);S.selected=c.id});}
function applyField(path,value){change(()=>{const [root,...parts]=path.split('.');let o=root==='screen'?screen():node();for(let i=0;i<parts.length-1;i++)o=o[parts[i]];const k=parts.at(-1);o[k]=['width','height','x','y'].includes(k)?Math.max(k==='width'||k==='height'?1:-100000,Math.round(Number(value)||0)):value;});}
async function copyAI(){await navigator.clipboard.writeText(makeAiHandoff(S.doc,S.screenId));toast('AI handoff copied');}
async function copyPNG(){const sc=screen(),blob=await svgToPngBlob(screenToSvg(sc),sc.width,sc.height);if(navigator.clipboard?.write&&window.ClipboardItem){await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);toast('PNG copied')}else{downloadBlob(`${safeFileName(sc.name)}.png`,blob);toast('PNG downloaded')}}
function exportJSON(){downloadText(`${safeFileName(S.doc.name)}.uib.json`,JSON.stringify(S.doc,null,2),'application/json;charset=utf-8');toast('Blueprint exported');}

$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
$('#copy-ai').onclick=()=>copyAI().catch(e=>toast(e.message)); $('#copy-preview').onclick=()=>copyPNG().catch(e=>toast(e.message)); $('#export-json').onclick=exportJSON; $('#import-json').onclick=()=>E.file.click();
E.file.onchange=async()=>{try{const imported=sanitizeDocument(JSON.parse(await E.file.files[0].text()));snapshot();S.doc=imported;S.screenId=imported.screens[0].id;S.selected=null;persist();render();fit();toast('Blueprint imported')}catch(e){toast(`Import failed: ${e.message}`)}E.file.value='';};
E.title.onchange=()=>change(()=>S.doc.name=E.title.value.trim()||'Untitled Blueprint');
$('#add-screen').onclick=()=>change(()=>{const sc=createScreen({name:`Screen ${S.doc.screens.length+1}`});S.doc.screens.push(sc);S.screenId=sc.id;S.selected=null});
E.screens.onclick=e=>{const r=e.target.closest('[data-screen]');if(r){S.screenId=r.dataset.screen;S.selected=null;render();fit();}};
E.layers.onclick=e=>{const h=e.target.closest('[data-hide]'),l=e.target.closest('[data-lock]');if(h)return change(()=>{const n=screen().nodes.find(x=>x.id===h.dataset.hide);n.hidden=!n.hidden;if(S.selected===n.id)S.selected=null});if(l)return change(()=>{const n=screen().nodes.find(x=>x.id===l.dataset.lock);n.locked=!n.locked});const r=e.target.closest('[data-node]');if(r){S.selected=r.dataset.node;setTool('select');render();}};
E.inspector.onchange=e=>{const f=e.target.closest('[data-field]');if(f)applyField(f.dataset.field,f.value);}; E.inspector.onclick=e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='delete')del();if(a==='duplicate')duplicate();if(a==='lock')change(()=>node().locked=!node().locked);};
E.stage.onpointerdown=e=>{if(S.space&&e.button===0){S.pan={x:e.clientX,y:e.clientY,left:E.stage.scrollLeft,top:E.stage.scrollTop};E.stage.classList.add('panning');e.preventDefault();}};
E.board.onpointerdown=e=>{if(S.space)return;const r=e.target.closest('[data-resize]');if(r)return beginResize(e,r.dataset.resize);const n=e.target.closest('.node');if(n)return beginNode(e,n.dataset.node);if(S.tool!=='select')beginDraw(e);else{S.selected=null;render();}};
E.board.ondblclick=e=>{const n=e.target.closest('.node');if(n){S.selected=n.dataset.node;setTool('select');render();requestAnimationFrame(()=>startTextEdit(S.selected));}};
window.onpointermove=e=>{if(S.pan){E.stage.scrollLeft=S.pan.left-(e.clientX-S.pan.x);E.stage.scrollTop=S.pan.top-(e.clientY-S.pan.y);return}drawMove(e);moveNode(e);resizeMove(e);}; window.onpointerup=e=>{if(S.pan){S.pan=null;E.stage.classList.remove('panning')}if(S.gesture?.kind==='draw')endDraw(e);else if(S.gesture?.kind==='move')endMove();else if(S.gesture?.kind==='resize')endResize();};
$('#zoom-in').onclick=()=>setZoom(S.zoom*1.12); $('#zoom-out').onclick=()=>setZoom(S.zoom/1.12); E.zoom.onclick=fit; E.grid.onclick=()=>{S.grid=!S.grid;render();};
window.onkeydown=e=>{if(e.target.matches('input,textarea,select'))return;if(e.code==='Space'){S.space=true;e.preventDefault();return}const meta=e.metaKey||e.ctrlKey;if(meta&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(meta&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();return}if(meta&&e.shiftKey&&e.key.toLowerCase()==='c'){e.preventDefault();copyAI();return}if(['Delete','Backspace'].includes(e.key)){e.preventDefault();del();return}if(e.key==='Enter'&&S.selected){e.preventDefault();startTextEdit(S.selected);return}if(e.key==='0'){e.preventDefault();fit();return}if(e.key.toLowerCase()==='g'){S.grid=!S.grid;render();return}const tools={v:'select',f:'frame',b:'box',t:'text',i:'image'};if(tools[e.key.toLowerCase()]){e.preventDefault();setTool(tools[e.key.toLowerCase()]);return}const arrows={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(arrows[e.key]&&node()&&!node().locked){e.preventDefault();const [dx,dy]=arrows[e.key],step=e.shiftKey?10:1;change(()=>{node().bounds.x+=dx*step;node().bounds.y+=dy*step});return}if(e.key==='+'||e.key==='=')setZoom(S.zoom*1.12);if(e.key==='-')setZoom(S.zoom/1.12);};
window.onkeyup=e=>{if(e.code==='Space')S.space=false};window.onblur=()=>{S.space=false;S.pan=null;E.stage.classList.remove('panning')};
document.onpointerover=e=>{const t=e.target.closest('[data-tooltip]');if(!t)return;clearTimeout(S.tipTimer);S.tipTimer=setTimeout(()=>{const [title,body='']=t.dataset.tooltip.split('|'),r=t.getBoundingClientRect();E.tipTitle.textContent=title;E.tipBody.textContent=body;E.tipBody.hidden=!body;E.tooltip.hidden=false;E.tooltip.style.left=`${Math.max(8,Math.min(innerWidth-285,r.left))}px`;E.tooltip.style.top=`${Math.min(innerHeight-70,r.bottom+8)}px`;status(body||title);},220);};
document.onpointerout=e=>{const t=e.target.closest('[data-tooltip]');if(!t||t.contains(e.relatedTarget))return;clearTimeout(S.tipTimer);E.tooltip.hidden=true;status();};
render(); requestAnimationFrame(fit);
